### ISSUE TITLE
[Enhancement] Disable Donut Hole When User Not Logged In

### ISSUE THREAD

**Issue by dazbradbury** [moonpyk/mvcdonutcaching#18]
I'm just doing some profiling on my code, and am wondering if it's possible to have Donut Hole caching disabled if `User.Identity.IsAuthenticated = false`?

My thinking is, if the user is not logged in, we simply serve from the cache immediately.

If a user is logged in, then we use the donut hole cache to fill in the user specific parts of the page - as it happens currently.

In terms of efficiency, it will surely be much faster to do it this way, than have several "Donut Holes", which check if a user is Logged in, and if not, put in the same standard code by replacement, into the output stream.

Ideally, I could create DonutHole Cache Categories, for example:

1) Not Logged In / Logged In
2) Is Mobile / Not Mobile User
3) Is Internet Explorer 7 User / Not IE7 User

Then the cache would populate different versions for each type (and combination of type).

As we're using an output cache to try and improve efficiency, it seems sensible to take it a step further. What do you think? Or does this already exist and I've just missed it?

**Comment by RickTheHat** [comment]
I'm currently looking to do this also, if you have a sample of the "code restructuring" you're talking about I'd love to see it. This package works as expected so areas like my Google Ads aren't cached but I don't with to do any caching when my users are logged in, I would think this is pretty basic functionality but apparently not as I don't see articles talking about this.

i.e. In my case, when a user is on a page & they leave a comment, I can update the comment list via ajax but when the user migrates away from the page and comes back, the comment is not there because the page is cached so that's why I don't want any caching when users are logged in.

on the flip side, if you come to the page as a non-logged in user, you're just reading the comments and that can be cached which saves me tons of db calls.
