### ISSUE TITLE
Azure Redis output cache provider issue

### ISSUE THREAD

**Issue by hpcsc** [moonpyk/mvcdonutcaching#35]
Hi,

I use the library in my ASP.NET MVC project, with Azure Redis output cache provider from Microsoft, but there is exception if I use DonutOutputCache attribute. Seem like the library cannot create instance of the output cache provider.

![image](https://cloud.githubusercontent.com/assets/5293047/5625982/b91a5b04-95bf-11e4-8fe3-fc3095c372c6.png)

My configuration is below. The configuration should have no problem because I use it with original OutputCache attribute and working fine

![image](https://cloud.githubusercontent.com/assets/5293047/5625973/9d140824-95bf-11e4-8177-9df1c8292572.png)

**Comment by michaelhaas88** [comment]
You have to use the provider like this:
![unbenannt](https://cloud.githubusercontent.com/assets/6052156/5936039/0114d1e6-a6e1-11e4-8ead-b53fa20e23ea.PNG)

**Comment by moonpyk** [comment]
So that's not a bug :)

**Comment by olaj** [comment]
I just want to add to this and maybe help someone.

The "type" attribute should be.

type="Microsoft.Web.Redis.RedisOutputCacheProvider,Microsoft.Web.RedisOutputCacheProvider"

What is hard to see (and you can't copy paste since it's an image) is that they are actually different. Copy paste the above and you should be fine.

**Comment by frankfuu** [comment]
Thanks for the heads up @olaj :)
